# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14fd73fa792e455f9a6bc27a327460fd1981445b48fb224f04df33c329d60beef2477a1f44920d737860eb98ea1c15e5edd3294078654eb4f1ba5f279d7dc161

test:
  secret_key_base: 6d69c8a357827a38f0289cc2044da5a9798c3d245329b566e07ddb31d8baa3cae21767cf8cea40f5dc36daefa69435817a35489283f82bce6ca4da274b85e50e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
